# Netlify deployment configuration (Frontend only)
[build]
  base = "frontend/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  REACT_APP_BACKEND_URL = "https://your-backend-url.herokuapp.com"
  REACT_APP_MONDAY_FORM_URL = "https://forms.monday.com/forms/a4a0b62dd139cdd5e5976c5f02ff6879?r=use1"

# Handle React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"